### ISSUE TITLE
You are not able to defend an enemy

### ISSUE THREAD

**Issue by SamuelRott** [oskarrough/slaytheweb#104]
When you play a Defend card and target an enemy the block power is added to the player.

Expected => the block power is added to the target, player or enemy.

Why ? 

1 - you can strike the enemy and the player so you should be able to do the same for defending
2 - in the future the game could include cards like "gain as much health as the enemy has blocks" thus you would want to stack the defend card on the enemy

**Comment by SamuelRott** [comment]
this is what causes the current behaviour: [link](https://github.com/oskarrough/slaytheweb/blob/a91305d25be51fb66155d56a24d6c9f4afd14cab/public/game/actions.js#L112)
```

		// Block is expected to always target the player.
		if (card.block) {
			draft.player.block = newState.player.block + card.block
		}
```
Its correct if you take the card.target in consideration, but then you should not be able to target the player with a "Strike" card.

**Comment by oskarrough** [comment]
Another good discussion! So…

It was not my intention that you can play defend cards on enemies. It was also not intended that you can attack yourself, but this - as you say - could enable some fun strategies.

I would say we continue to allow attacking yourself, but defend/block should not be allowed on an enemy. I don't think it is necessary now?

All cards should specify a `target` property to indicate, where the card can be played. Example: https://github.com/oskarrough/slaytheweb/blob/master/public/game/cards.js#L13. But it's probably not 100% respected through the code atm..

**Comment by oskarrough** [comment]
We could also decide to disallow attacking yourself for now to avoid more issues… and reopen again later, if we really want.
