### ISSUE TITLE
Thinking about more advanced cards

### ISSUE THREAD

**Issue by oskarrough** [oskarrough/slaytheweb#109]
Right now cards can…

- deal `damage`
- gain `block`
- apply `powers` that decay by 1 per turn (regen, vulnerable, weak)
- define `conditions` whether they are allowed to play

This is great and enough for version 1 of the game. But for the future as we implement more cards we can imagine much more FUN (read: complicated) logic in cards. Here are some examples that are currently NOT possible:

- "Deal 5 damage. Draw 1 card"
- "Gain 5 block. Gain 1 energy next turn"
- "Deal 5 damage. If the target is vulnerable, gain 1 energy and draw 1 card"
- "Double your block"
- "Add a random card to your hand"

Here are more card examples: [list of Slay the Spire cards](https://maybelatergames.co.uk/tools/slaythespire/tierlist/cards/ironclad/) & https://fiiiiilth.github.io/seeker/cardlist.html.

How would we do this?

Again taking inspiration from Slay the Spire, cards have an optional `use` method where you define an external `action` that the game will run whenever the card is played. Here are some examples:

```js
// new external "card" actions that cards can reuse
function drawCard(amount) {}
function gainEnergy(amount() {}
function multiplyBlock(amount) {}

{
  name: 'Example Card',
  type: 'Attack',
  energy: 2,
  damage: 5,
  target: 'enemy',
  description: 'Deal 5 damage. If target is vulnerable gain 1 energy and draw 1 card',
  use(game, target) {
    if (target.powers.vulnerable) {
      game.enqueue({type: 'drawCard', amount: 1})
      game.enqueue({type: 'gainEnergy', amount: 1})
    }
  }
},
```

This `use()` method would need access to the game `state` AND the `target` the card was played against.

**Comment by oskarrough** [comment]
If everything is defined as `actions` (which have access to the entire game state) they could even be reused for https://github.com/oskarrough/slaytheweb/issues/31.

**Comment by SamuelRott** [comment]
Hello, 

It might seems messy but I am for implementing the maximum of ideas on how to solve more complexity. One will simply appear superior after a few try, if not it means we have more then one good solution :).
As I dont fully grasp the flow of the game I dont really have a view on where or how to put this logic. But I guess I can catch up while we talk about this subject :).
 
Maybe random question, do we already have a way to know the previousPlayedCard ? for a scenario like "can only be played after a skill"
