### ISSUE TITLE
How do we create new cards

### ISSUE THREAD

**Issue by SamuelRott** [oskarrough/slaytheweb#115]
Right now cards a Js object containing properties and methods.

Its cumbersome to add new cards, imagine in the future where you have 100. As a dev I want a way to choose a set of cards without having to comment/uncomment code. It could be done by a filtering/choose your starting hand feature.

The actual setup is actually perfect to link to an api, we could use this api to create new cards using a form.
Far fetch future, each user could have his own cards/rules or get the cards/rules form the "original" game.

**Comment by oskarrough** [comment]
Not exactly an answer but some thoughts on how I think about logic and content in the current state of the code.

The content we have are the cards and dungeon/monsters.

The logic we have is 

1) all the actions that modify the game state 
2) the cards that can trigger actions with their properties, like `damage: 6` and soon a way to have more advanced logic reusing actions

As a use case, lets say you want to create a spaced themed version of this game. You would 1) create your own cards 2) create your own dungeon. Which starter deck, cards and dungeon you use is all defined inside ui/app and NOT part of the game logic.

A card could be added to your deck like this

```
const card =
{
		name: 'Mega Defend',
		type: 'Skill',
		energy: 3,
		block: 30,
		target: 'player',
		description: 'Gain 30 Block.',
	},
game.state.deck.push(card)
```

it's pretty easy no? Or which parts could we improve?

Example of how the starter deck is created: https://github.com/oskarrough/slaytheweb/blob/master/public/game/actions.js#L39-L56

**Comment by SamuelRott** [comment]
I made some test around and the conclusions are: 
```
const addedCard =
{
		name: 'Mega Defend',
		type: 'Skill',
		energy: 3,
		block: 30,
		target: 'player',
		description: 'Gain 30 Block.',
	},
this.game.state.deck.push(new Card(addedCard));
``` 

will create a bug regarding the **target** since the addedCard needs to be in the original cards array in game/cards.js. 
https://github.com/oskarrough/slaytheweb/blob/97fe88d19738478323fc4abd50065409a78a9a0a/public/ui/dragdrop.js#L16

If I follow **Which starter deck, cards and dungeon you use is all defined inside ui/app and NOT part of the game logic.** then the original cards array in game/cards.js should maybe be part of the ui logic and not contain any code ?

**Comment by oskarrough** [comment]
Ah you're right. The dragdrop stuff needs to be activated whenever the "hand" is modified.. But that should be another improvement issue we can open 👍 Would be sweet if it could bind to whatever elements are in the hand by itself.

For now to deal with it, call the `dealCards()` method in app.js.

Hmm... maybe we are going too deep here, but I see what you mean. This is very hypotheic, but say we wanted to implement a version of the game for PlayStation. A new UI. It's a new platform we can't reuse `ui/app.js` but we can and want to use everything inside `game` including the cards. If we want new cards, the `game` contains the logic to create them.

**Comment by oskarrough** [comment]
Or we just think about the cards and dungeon as the default ones? Easy to overwrite. If you want another dungeon, you only have to set `game.state.dungeon` to a different object.
