### ISSUE TITLE
Why did you nerf flourish!!

### ISSUE THREAD

**Issue by hugurp** [oskarrough/slaytheweb#126]
Now i keep loosing this game! IS THIS AI OR WHAT?

**Comment by oskarrough** [comment]
![](https://media.giphy.com/media/YQk8nXloVftzW/giphy.gif)

**Comment by oskarrough** [comment]
wait, it really isn't working. It can currently always be played. It's also boring if you can never play it. Will make it so you can always play, but for 3 energy?
