### ISSUE TITLE
Problems with floor boss

### ISSUE THREAD

**Issue by za3k** [oskarrough/slaytheweb#153]
![2021-08-29-013654_1920x1080_scrot](https://user-images.githubusercontent.com/726482/131244236-2b786c97-1aac-4469-b248-4e93db4119e5.png)

On the floor boss, dragging a card to the boss duplicates it. Clicking "End turn" removes my cards but doesn't deal new ones.

**Comment by oskarrough** [comment]
Wow that's a great screenshot, thank you for reporting. Not yet sure what's going on though…

If you catch something similar again, could you share the save game? Open the "Escape" menu top left and press "Save" and copy the URL here. Then I can inspect the game state and hopefully see what's up.

**Comment by oskarrough** [comment]
I made it to the boss today (only took a year) and didn't experience any errors. That's not to there isn't one, but I'm closing this issue until we manage to find it again.
