### ISSUE TITLE
License violation for fonts?

### ISSUE THREAD

**Issue by typesanitizer** [oskarrough/slaytheweb#156]
https://mbtype.com/license/

> Copies of my fonts cannot be distributed to anyone
> who is not a licensed user. Nor can my fonts be stored
> in a location accessible to those who are not licensed
> users (e.g., a file server or source repository).

I noticed that the Heliotrope Woff files are checked
into source control, so anyone can access them.

However, there is also this in point 8.

> There are three exceptions to ¶ 7. First: read-only copies
of my fonts can be embedded in digital files, including
PDFs, e-books, and software apps. Read-only means
that those who use these digital files can neither install
my fonts nor use them to make new documents. Second:
the webfonts (= WOFF2 files) can be used on up
to three websites owned by the license buyer

So I'm not sure if that means that it's OK to check the WOFF
files into source control.

**Comment by oskarrough** [comment]
I'm honestly not certain whether the license permits checking the font files into source control. I reasoned that any website using web fonts will have to make the WOFF2 files accessible one way or the other. You can't restrict it technically, hence the license. I'll ask the him to make sure.

Thank you!

**Comment by mbutterick** [comment]
> I'm honestly not certain whether the license permits checking the font files into source control.

As @typesanitizer correctly points out, [my license](http://mbtype.com/license) explicitly forbids storing the fonts in a public source repository:

> Nor can my fonts be stored in a location accessible to those who are not licensed
users (e.g., a file server or source repository).

Yes, you can still put the fonts on a public web server as part of a website design ([for instance](https://oskarrough.com/styles/index.css)). The reason for the source-repository limitation is explained [in the FAQ](http://mbtype.com/faq):

> **Why can’t I store the fonts in a public source repository?**
> Because on sites like GitHub, people assume everything in a public repository can be freely copied, even if the license says otherwise. It’s a major vector of unlicensed font usage. (Storing the fonts in a private repository is fine, however.)

`slaytheweb` is unfortunately an example of why this restriction exists. This repository is licensed under the [AGPL-3.0](https://github.com/oskarrough/slaytheweb/blob/main/LICENSE). This means you are claiming to relicense my fonts under the AGPL. As nicely as possible, this is a major violation of my license, which is not compatible with any open-source license.

I need to ask that you please either a) convert this repository to private, or b) rewrite the Git history to remove my fonts (including Heliotrope and [Concourse](https://github.com/oskarrough/slaytheweb/commit/edb52a65a8a28b415b5144757ddbb3de6aa84d43) and whatever others might have been used). 

To be clear: it’s fine if you use my WOFF2 files on the public [Slay the Web](https://slaytheweb.cards/) website. That is allowed by my license. I also don’t mind if the AGPL source code refers to the fonts. But the build script should fetch them from some private location on your local machine, so they don’t need to be in the repo.

“But then the build won’t work the same way on other machines.” No, it won’t. But that’s an easier problem to work around, and it’s the only way you can comply with my license while having the rest of your code under the AGPL.

**Comment by oskarrough** [comment]
Sorry about this, @mbutterick. Even more as a fan of your typefaces. I very much appreciate you taking the time to explain and being so helpful.

The fonts have now been removed from the entire git history. I followed the steps outlined by the [git filter-repo](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html) tool.
