### ISSUE TITLE
The website is now a white screen on firefox w/ windows.

### ISSUE THREAD

**Issue by Vesper-arch** [oskarrough/slaytheweb#228]
It shows in inspect this error: `Failed to load ‘https://slaytheweb.cards/ui/index.js’. A ServiceWorker intercepted the request and encountered an unexpected error.` Don't know what that means but hopefully you do. Edit: It works on mobile though.

**Comment by oskarrough** [comment]
Hey, thanks. Here it does load in Firefox on Windows though. Could you try clearing your browser cache for slaytheweb.cards? Maybe the service worker I've configured is caching things too hard.

**Comment by Vesper-arch** [comment]
Ok, that fixed it. My bad.
