### ISSUE TITLE
Can attack dead enemies

### ISSUE THREAD

**Issue by necipallef** [oskarrough/slaytheweb#239]
I can attack the enemies that I already killed, and it uses the card and spends the energy. It shouldn't let me target dead enemies.

**Comment by oskarrough** [comment]
Aha, thank you.

There's a utility function that returns true/false if the card has a valid target.

https://github.com/oskarrough/slaytheweb/blob/0b4b617db5ea3c20fc97fd516cee2ed555de2235/src/game/utils-state.js#L72-L78

There's also `playCard()` action that does a few checks to see whether you can play the card. Is it the right target, do you have enough energy etc.

https://github.com/oskarrough/slaytheweb/blob/0b4b617db5ea3c20fc97fd516cee2ed555de2235/src/game/actions.js#L211-L215

Somewhere in one of those we should check if the target has healthn or not.

**Comment by oskarrough** [comment]
Hey @necipallef, thanks again for finding this. It is now fixed on https://slaytheweb.cards
